name: Deploy to Heroku

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dev dependencies
        run: pip install -r requirements.txt

      - name: Check Lint
        run: task format

      - name: Build and running tests
        run: |
          pytest -vvv --cov=src tests/

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token > ~/.netrc && heroku container:login

      - name: Build and push Docker image to Heroku
        run: |
          heroku container:push web -a api-example-mongodb

      - name: Release the Docker image
        run: |
          heroku container:release web -a api-example-mongodb
